name: Deploy DDF

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Terraform Init
      env:
        TF_VAR_resource_group_name: "ddf-resource-group"
        TF_VAR_location: "East Asia"
        TF_VAR_api_management_name: "ddf-api-management-ken"
        TF_VAR_publisher_email: "23088695@siswa365.um.edu.my"
        TF_VAR_publisher_name: "Ken"
        TF_VAR_sku_name: "Developer_1"
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      env:
        TF_VAR_resource_group_name: "ddf-resource-group"
        TF_VAR_location: "East Asia"
        TF_VAR_api_management_name: "ddf-api-management-ken"
        TF_VAR_publisher_email: "23088695@siswa365.um.edu.my"
        TF_VAR_publisher_name: "Ken"
        TF_VAR_sku_name: "Developer_1"
      run: terraform plan
      working-directory: ./terraform

    - name: Terraform Apply
      env:
        TF_VAR_resource_group_name: "ddf-resource-group"
        TF_VAR_location: "East Asia"
        TF_VAR_api_management_name: "ddf-api-management-ken"
        TF_VAR_publisher_email: "23088695@siswa365.um.edu.my"
        TF_VAR_publisher_name: "Ken"
        TF_VAR_sku_name: "Developer_1"
      run: terraform apply -auto-approve
      working-directory: ./terraform
