name: Deploy DDF

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Terraform Init
      env:
        TF_VAR_resource_group_name: "ddf-resource-group"
        TF_VAR_location: "East Asia"
        TF_VAR_api_management_name: "ddf-api-management-ken"
        TF_VAR_publisher_email: "23088695@siswa365.um.edu.my"
        TF_VAR_publisher_name: "Ken"
        TF_VAR_sku_name: "Developer_1"
        TF_VAR_client_id: "97a7b001-c497-4516-9166-2815a55b8d51"
        TF_VAR_client_secret: "mZc8Q~H6eYzTrjDIUjUyx.AnSdQh0rntPFAFCcfA"
        TF_VAR_subscription_id: "5dee684c-5ea6-42bc-bedb-9e31d667a3df"
        TF_VAR_tenant_id: "a63bb1a9-48c2-448b-8693-3317b00ca7fb"
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      env:
        TF_VAR_resource_group_name: "ddf-resource-group"
        TF_VAR_location: "East Asia"
        TF_VAR_api_management_name: "ddf-api-management-ken"
        TF_VAR_publisher_email: "23088695@siswa365.um.edu.my"
        TF_VAR_publisher_name: "Ken"
        TF_VAR_sku_name: "Developer_1"
        TF_VAR_client_id: "97a7b001-c497-4516-9166-2815a55b8d51"
        TF_VAR_client_secret: "mZc8Q~H6eYzTrjDIUjUyx.AnSdQh0rntPFAFCcfA"
        TF_VAR_subscription_id: "5dee684c-5ea6-42bc-bedb-9e31d667a3df"
        TF_VAR_tenant_id: "a63bb1a9-48c2-448b-8693-3317b00ca7fb"
      run: terraform plan
      working-directory: ./terraform

    - name: Terraform Apply
      env:
        TF_VAR_resource_group_name: "ddf-resource-group"
        TF_VAR_location: "East Asia"
        TF_VAR_api_management_name: "ddf-api-management-ken"
        TF_VAR_publisher_email: "23088695@siswa365.um.edu.my"
        TF_VAR_publisher_name: "Ken"
        TF_VAR_sku_name: "Developer_1"
        TF_VAR_client_id: "97a7b001-c497-4516-9166-2815a55b8d51"
        TF_VAR_client_secret: "mZc8Q~H6eYzTrjDIUjUyx.AnSdQh0rntPFAFCcfA"
        TF_VAR_subscription_id: "5dee684c-5ea6-42bc-bedb-9e31d667a3df"
        TF_VAR_tenant_id: "a63bb1a9-48c2-448b-8693-3317b00ca7fb"
      run: terraform apply -auto-approve
      working-directory: ./terraform
